name: misti
description: Connect to your Misti Mask.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.16.2
  permission_handler: ^10.4.3
  flame: any
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/ground2.png
    - assets/images/MistiCloud.png
    - assets/images/Pillow.png
    - assets/images/
    - assets/audio/
    - assets/images/menu.jpg
    - assets/images/message.png
    - assets/images/gameover.png