name: misti
description: Connect to your Misti Mask.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  permission_handler: ^11.3.1
  flame: any
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  intl: ^0.20.0
  path_provider: ^2.1.5
  flame_audio: ^2.10.6
  shared_preferences: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/flappyBirdGames/ground2.png
    - assets/images/MistiCloud.png
    - assets/images/Pillow.png
    - assets/images/
    - assets/images/flappyBirdGames/
    - assets/audio/
    - assets/images/flappyBirdGames/menu.jpg
    - assets/images/flappyBirdGames/message.png
    - assets/images/flappyBirdGames/gameover.png
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/images/tutorial1.png
    - assets/images/tutorial2.png
    - assets/images/tutorial3.png